### ISSUE TITLE
scaffold task accepts invalid column name

### ISSUE THREAD

**Issue by bigwheel** [skinny-framework/skinny-framework#262]
scaffold task accepts _(underscore) only column name, and it must not work

``` bash
 % ./skinny g scaffold lanePrefOrders lanePrefOrder name:String _:Int
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
[info] Loading global plugins from /home/kbigwheel/.sbt/0.13/plugins
[info] Loading project definition from /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/project
[info] Set current project to skinny-blank-app-dev (in build file:/home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/)
[info] Updating {file:/home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/}dev...
[info] Resolving org.eclipse.jetty#jetty-jndi;9.2.10.v20150310 ...
[info] Done updating.
[info] Updating {file:/home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/}task...
[info] Resolving org.eclipse.jetty#jetty-jndi;9.2.10.v20150310 ...
[info] Done updating.
[info] Generating /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/task/target/scala-2.11/resource_managed/main/rebel.xml.
[info] Generating /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/target/dev/scala-2.11/resource_managed/main/rebel.xml.
[info] Running TaskRunner generate:scaffold lanePrefOrders lanePrefOrder name:String _:Int

 *** Skinny Generator Task ***

  "src/main/scala/controller/ApplicationController.scala" skipped.
  "src/main/scala/controller/LanePrefOrdersController.scala" created.
  "src/main/scala/controller/Controllers.scala" modified.
  "src/test/scala/controller/LanePrefOrdersControllerSpec.scala" created.
  "src/test/scala/integrationtest/LanePrefOrdersController_IntegrationTestSpec.scala" created.
  "src/test/resources/factories.conf" modified.
  "src/main/scala/model/LanePrefOrder.scala" created.
  "src/test/scala/model/LanePrefOrderSpec.scala" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/_form.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/new.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/edit.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/index.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/show.html.ssp" created.
  "src/main/resources/messages.conf" modified.
  "src/main/resources/db/migration/V20150603233606__Create_lanePrefOrders_table.sql" created.

[success] Total time: 1 s, completed 2015/06/03 23:36:06
./skinny g scaffold lanePrefOrders lanePrefOrder name:String _:Int  32.13s user 1.04s system 246% cpu 13.451 total
```

In another sample,  underscore start column name causes exception.

```
 % ./skinny g scaffold lanePrefOrders lanePrefOrder name:String _abc:Int
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar
[info] Loading global plugins from /home/kbigwheel/.sbt/0.13/plugins
[info] Loading project definition from /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/project
[info] Set current project to skinny-blank-app-dev (in build file:/home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/)
[info] Generating /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/task/target/scala-2.11/resource_managed/main/rebel.xml.
[info] Generating /home/kbigwheel/Dropbox/workspaces/IdeaProjects/lol-lane-optimizer/target/dev/scala-2.11/resource_managed/main/rebel.xml.
[info] Running TaskRunner generate:scaffold lanePrefOrders lanePrefOrder name:String _abc:Int

 *** Skinny Generator Task ***

  "src/main/scala/controller/ApplicationController.scala" skipped.
  "src/main/scala/controller/LanePrefOrdersController.scala" created.
  "src/main/scala/controller/Controllers.scala" modified.
  "src/test/scala/controller/LanePrefOrdersControllerSpec.scala" created.
  "src/test/scala/integrationtest/LanePrefOrdersController_IntegrationTestSpec.scala" created.
  "src/test/resources/factories.conf" modified.
  "src/main/scala/model/LanePrefOrder.scala" created.
  "src/test/scala/model/LanePrefOrderSpec.scala" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/_form.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/new.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/edit.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/index.html.ssp" created.
  "src/main/webapp/WEB-INF/views/lanePrefOrders/show.html.ssp" created.
[error] (run-main-0) java.util.NoSuchElementException: next on empty iterator
java.util.NoSuchElementException: next on empty iterator
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
        at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
        at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
        at scala.collection.IterableLike$class.head(IterableLike.scala:107)
        at scala.collection.immutable.StringOps.scala$collection$IndexedSeqOptimized$$super$head(StringOps.scala:30)
        at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:126)
        at scala.collection.immutable.StringOps.head(StringOps.scala:30)
        at skinny.task.generator.CodeGenerator$$anonfun$toCapitalizedSplitName$1.apply(CodeGenerator.scala:180)
        at skinny.task.generator.CodeGenerator$$anonfun$toCapitalizedSplitName$1.apply(CodeGenerator.scala:180)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at skinny.task.generator.CodeGenerator$class.toCapitalizedSplitName(CodeGenerator.scala:180)
        at skinny.task.generator.ScaffoldSspGenerator$.toCapitalizedSplitName(ScaffoldSspGenerator.scala:8)
        at skinny.task.generator.ScaffoldGenerator$$anonfun$messagesConfCode$1.apply(ScaffoldGenerator.scala:594)
        at skinny.task.generator.ScaffoldGenerator$$anonfun$messagesConfCode$1.apply(ScaffoldGenerator.scala:594)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at skinny.task.generator.ScaffoldGenerator$class.messagesConfCode(ScaffoldGenerator.scala:594)
        at skinny.task.generator.ScaffoldSspGenerator$.messagesConfCode(ScaffoldSspGenerator.scala:8)
        at skinny.task.generator.ScaffoldGenerator$class.generateMessages(ScaffoldGenerator.scala:601)
        at skinny.task.generator.ScaffoldSspGenerator$.generateMessages(ScaffoldSspGenerator.scala:8)
        at skinny.task.generator.ScaffoldGenerator$class.run(ScaffoldGenerator.scala:123)
        at skinny.task.generator.ScaffoldSspGenerator$.run(ScaffoldSspGenerator.scala:8)
        at skinny.task.DefaultTaskLauncher$$anonfun$4.apply(DefaultTaskLauncher.scala:17)
        at skinny.task.DefaultTaskLauncher$$anonfun$4.apply(DefaultTaskLauncher.scala:17)
        at skinny.task.SkinnyTaskLauncher$$anonfun$main$2.apply(SkinnyTaskLauncher.scala:25)
        at skinny.task.SkinnyTaskLauncher$$anonfun$main$2.apply(SkinnyTaskLauncher.scala:25)
        at scala.Option.map(Option.scala:146)
        at skinny.task.SkinnyTaskLauncher$class.main(SkinnyTaskLauncher.scala:25)
        at TaskRunner$.main(TaskRunner.scala:1)
        at TaskRunner.main(TaskRunner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last task/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last task/compile:run for the full output.
[error] (task/compile:run) Nonzero exit code: 1
[error] Total time: 1 s, completed 2015/06/03 23:41:14
./skinny g scaffold lanePrefOrders lanePrefOrder name:String _abc:Int  18.97s user 0.76s system 241% cpu 8.180 total
```

I guess column name validation is needed in near [here](https://github.com/skinny-framework/skinny-framework/blob/master/task/src/main/scala/skinny/task/generator/ScaffoldGenerator.scala#L60).
I thought appropriate validation rule several minutes, but I dont know skinny well yet.
I gave up soon.

**Comment by seratch** [comment]
Thanks. IMO, this issue doesn't feature high on our list of priorities, but fixing them would be better.

**Comment by bigwheel** [comment]
Ok, I try to fix this later.
