### ISSUE TITLE
Skinny + Scalajs problem

### ISSUE THREAD

**Issue by matiastoro** [skinny-framework/skinny-framework#315]
Hi,

I've been trying to make a skinny app to work with scalajs. I followed the instructions of http://skinny-framework.org/documentation/assets.html but with no success.
 
I put my scalajs code here:
webapp/WEB-INF/assets/scala/Application.scala

```
import scala.scalajs.js.JSApp

object Application extends JSApp {
  def main(): Unit = {
    println("Hello world!")
  }
}
```
and then run "skinny scalajs:watch" to generate the javascript files.

The problem is that I don't know how to access to the resulting javascripts. I've tried
http://localhost:8080/assets/js/application.js
and 
http://localhost:8080/assets/js/application-fastopt.js

with no success.

The link http://localhost:8080/assets/js/application.js gives me a:
```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at skinny.controller.assets.AssetCompiler$class.findRealFile(AssetCompiler.scala:50)
	at skinny.controller.assets.ScalaJSAssetCompiler$.findRealFile(ScalaJSAssetCompiler.scala:6)
	at skinny.controller.AssetsController$$anonfun$compiledCodeFromFile$1.apply(AssetsController.scala:387)
	at skinny.controller.AssetsController$$anonfun$compiledCodeFromFile$1.apply(AssetsController.scala:385)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
....
```

and the link http://localhost:8080/assets/js/application-fastopt.js gives me:
```
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:203)
	at java.io.BufferedReader.read(BufferedReader.java:279)
	at java.io.Reader.read(Reader.java:140)
        ...
```

The only link that does work is http://localhost:8080/assets/js/application-jsdeps.js

Can you help me with this problem?

Thanks!

**Comment by seratch** [comment]
Thank you for reporting.

> http://localhost:8080/assets/js/application.js

As you pointed out, NPE occurs. This problem should be fixed.

>http://localhost:8080/assets/js/application-fastopt.js

Not sure about this. The URL works on my local machine.
